/*
 * Copyright 2016 MovingBlocks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.terasology.calendar.events;

import org.terasology.entitySystem.event.Event;

/**
 * A calendar event generated by CalendarSystem.
 * For each of the main calendar units, there are three events to choose from.
 * <ul>
 *  <li>Event - fired whenever a unit begins or ends</li>
 *  <li>Start - fired at the beginning of the day when a unit begins</li>
 *  <li>End - fired at the end of the day when a unit ends</li>
 * </ul>
 * Note the Event type always fires with Start and End events.
 */
public class OnCalendarEvent implements Event {

    /**
     * The year in which the event occurs.
     */
    int year;

    /**
     * The number of the unit.
     */
    int unit;

    /**
     * Creates the new event.
     * @param yearNumber The year in which the event occurs.
     * @param unitNumber The number of the unit.
     */
    public OnCalendarEvent(int yearNumber, int unitNumber) {
        year = yearNumber;
        unit = unitNumber;
    }

    /**
     * Get the unit number, for example 1 for the second month
     * @return Unit number.
     */
    public int getUnit() {
        return unit;
    }

    /**
     * Get the year in which the event is occurring.
     * @return The year.
     */
    public int getYear() {
        return year;
    }
}
